<section>    
        <nav>
            <div class="container main-nav flex">
                <a href="#" class="company-logo">
                    <img src="images/1e8db9d5-8587-4e13-b369-8c442fbc2737.jpeg" alt="company logo">
                </a>
                <div class="nav-links" id="nav-links">
                    <ul class="flex">
                       
                        <li><a href="about.php" class="hover-link">About</a></li>
                        <li><a href="display.php" class="hover-link">Jobs</a></li>
			<li><a href="enhancement2.php" class="hover-link">Enhancements</a></li>
			 <li><a href="index.php" id="signup-button" class="hover-link primary-button">Home</a></li>
                        <li><a href="apply.php" class="hover-link secondary-button">Apply</a></li>
                        <li><a href="registration.php" class="hover-link secondary-button">Manager</a></li>
                    </ul>
                </div>
            </div>
        </nav>
</section>

    